### ISSUE TITLE
Игра не готова!

### ISSUE THREAD

**Issue by He4eT** [AngryMushroom/TimberRush#1]
Привет! Молодец, что завел репозиторий.
Готовность демо-версии можно обозначить комментарием к этом Issue, а релиз - закрытием.
Успехов и идей =)

**Comment by Danand** [comment]
Демо готово. Скачать: [тут](https://dl.dropboxusercontent.com/u/111424884/TimberRush_v0.0.0.1.zip).

**Управление:**
WASD – передвижение, Space – атака.

**Суть:**
Стилизованный аркадный сурвайвал хоррор про лес и клетчатую рубашку.

**Готовность:**
Меньше, чем хотелось бы на данный момент. Но все ещё впереди, ведь так? 😈

**Comment by He4eT** [comment]
Привет. Сам ходи по своей битой ссылке :(
https://dl.dropboxusercontent.com/u/111424884/TimberRush_v0.0.0.1.zip

**Comment by Danand** [comment]
Актуальная сборка отправлена на почту UGJ.
